const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync(__dirname + '/index.html', 'utf8');
const elements = Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m => [m[1], {textContent:'', style:{}, hidden:false}]));
let clock = 10000, tick;
class TestDate extends Date { static now() { return clock; } }
const context = vm.createContext({document:{getElementById:id=>{assert.ok(elements[id],id);return elements[id];}}, navigator:{serial:{}}, Date:TestDate, setInterval:fn=>{tick=fn}, TextDecoder, console});
vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1], context);
function line(data) { context.sample='[ESWS'+(data.sensor==='ES-WS-02'?'02':'04')+'] '+JSON.stringify(data); vm.runInContext('processLine(sample)',context); }
line({sensor:'ES-WS-02',status:'ok',speed_mps:3.6,baud:4800});
assert.equal(elements.speed.textContent,'3.6');
assert.equal(elements.speedKmh.textContent,'12.96 km/h');
assert.equal(elements.compass.hidden,false);
line({sensor:'ES-WS-04',status:'ok',angle_deg:351.2,direction:'N',address:1,baud:4800});
assert.equal(elements.angle.textContent,'351.2°');
assert.equal(elements.speed.textContent,'3.6');
assert.equal(elements.speedPanel.hidden,false);
line({sensor:'ES-WS-02',status:'ok',speed_mps:0});
assert.equal(elements.speed.textContent,'0.0');
line({sensor:'ES-WS-02',status:'timeout',speed_mps:null});
assert.equal(elements.speed.textContent,'—');
assert.equal(elements.angle.textContent,'351.2°');
line({sensor:'ES-WS-02',status:'ok',speed_mps:null});
assert.match(elements.speedStatus.textContent,/invalid_data/);
line({sensor:'ES-WS-04',status:'ok',angle_deg:351.2,direction:'N'});
assert.equal(elements.angle.textContent,'351.2°');
assert.equal(elements.speedPanel.hidden,false);
line({sensor:'ES-WS-02',status:'ok',speed_mps:1.2});
vm.runInContext('reading=true; connectedAt=Date.now()',context);
clock+=4000;
line({sensor:'ES-WS-04',status:'ok',angle_deg:90,direction:'E'});
tick();
assert.match(elements.speedStatus.textContent,/3,5/);
assert.equal(elements.speed.textContent,'—');
assert.equal(elements.angle.textContent,'90.0°');
line({sensor:'ES-WS-02',status:'ok',speed_mps:2.5});
assert.equal(elements.speed.textContent,'2.5');
assert.match(elements.serialState.textContent,/cả hai/);
line({sensor:'ES-WS-04',status:'bad_crc',angle_deg:null});
assert.equal(elements.angle.textContent,'—°');
assert.equal(elements.speed.textContent,'2.5');
assert.match(elements.serialState.textContent,/1\/2/);
console.log('PASS: concurrent values, independent errors/stale/recovery, zero, scaling, sensor status');
